#ifndef KERNEL_ARCH_X86_64_DRIVERS_QEMU_SERIAL_PORT_QEMU_SERIAL_PORT_HPP_
#define KERNEL_ARCH_X86_64_DRIVERS_QEMU_SERIAL_PORT_QEMU_SERIAL_PORT_HPP_

#include <comp.h>

DEF_MULTITARGET_FUNC(void, QemuSerialPortInit, ());
DEF_MULTITARGET_FUNC(void, QemuSerialPortPutChar, (char c));
DEF_MULTITARGET_FUNC(void, QemuSerialPortPuts, (const char *str));

#endif // KERNEL_ARCH_X86_64_DRIVERS_QEMU_SERIAL_PORT_QEMU_SERIAL_PORT_HPP_
