# Place your configuration here:
# TODO: file in work, will be changed in PR with CI/CD and cmake fixes
# ALKOS_ISO_PATH=...
# ALKOS_BIN_PATH=...
# ALKOS_BUILD_DIR=...
# ALKOS_TOOLS_DIR=...
# ALKOS_TOOLCHAIN_PATH=...

export ALKOS_QEMU_ARGS="-serial stdio -enable-kvm -cpu host"
export ALKOS_ISO_PATH="/home/Jlisowskyy/Storage/Repos/AlkOS/alkos/build/gcc-debug/alkos.iso"
