# Place your configuration here:
# TODO: file in work
# ALKOS_ISO_PATH=...
# ALKOS_BIN_PATH=...
# ALKOS_BUILD_DIR=...
# ALKOS_TOOLS_DIR=...
# ALKOS_TOOLCHAIN_PATH=...

export ALKOS_QEMU_ARGS="-serial stdio -enable-kvm -cpu host"
export ALKOS_ISO_PATH="/home/Jlisowskyy/Repos/AlkOS/alkos/build/gcc-cross-debug/alkos.iso"
