//
// Created by wookie on 1/4/25.
//

#ifndef ALK_OS_KERNEL_ARCH_X86_64_BOOT32_INCLUDE_TAGS_HPP
#define ALK_OS_KERNEL_ARCH_X86_64_BOOT32_INCLUDE_TAGS_HPP

#define INFO_TAG    "[INFO]      "
#define ERROR_TAG   "[ERROR]     "
#define SUCCESS_TAG "[SUCCESS]   "

#endif // ALK_OS_KERNEL_ARCH_X86_64_BOOT32_INCLUDE_TAGS_HPP
